### ISSUE TITLE
unrecognized arguments: --engine-mode test_wav

### ISSUE THREAD

**Issue by lucellent** [dmlguq456/SepReformer#10]
I can't seem to inference with the provided checkpoints.

Also how do I specify my input file? There aren't any arguments or folders for that...

**Comment by dmlguq456** [comment]
Currently, inference for individual samples is not supported, as the 'test_wav' mode is primarily saving purposes. However, we plan to implement this feature in the near future. Thank you for your patience, and we appreciate your understanding as we work on this improvement.
Also, to avoid confusion, I will rename the existing `test_wav` function to `test_save`.

Thank you.

**Comment by lucellent** [comment]
I understand, thank you!

Follow up question - I noticed all models are trained only on 8000khz sample rate, if I change it to 44100 in the config will it work or not since that's outside of the model capabilities?
